enable_debug_for_user_ids:   
  type: list
  default: "2|42"
  list_type: simple
  regex: "^\\d+$"
  description: "Enable debug for specific users by numeric ID"
enable_debug_for_admins:
  type: bool
  default: true
  description: ""
enable_debug_for_all:
  type: bool
  default: false
  description: ""
show_on:
  default: homepage
  type: enum
  choices:
    - homepage
    - all
  description: custom tiles

plugin_outlet:
  default: "above-main-container"
  type: enum
  choices:
    - above-main-container
    - below-site-header

enable_banner_above_tiles:
  type: bool
  default: false
  description: "Enable to show a banner above tiles"

banner_image:
  type: upload
  default: ""
  description: "Image for the banner above the tiles"

enable_tile_images:
  type: bool
  default: false
  description: "Enable to show the tiles images"

tile_1_image:
  type: upload
  default: ""
  description: "Image for tile 1"

tile_2_image:
  type: upload
  default: ""
  description: "Image for tile 2"

tile_3_image:
  type: upload
  default: ""
  description: "Image for tile 3"

tile_4_image:
  type: upload
  default: ""
  description: "Image for tile 4"

show_for:
  default: everyone
  type: enum
  choices:
    - everyone
    - logged_in
    - logged_out
