show_on:
  default: homepage
  type: enum
  choices:
    - homepage
    - all
  description: custom tiles

plugin_outlet:
  default: "above-main-container"
  type: enum
  choices:
    - above-main-container
    - below-site-header

tile_1_image:
  type: upload
  default: ""
  description: image for tile 1

tile_2_image:
  type: upload
  default: ""
  description: image for tile 2

tile_3_image:
  type: upload
  default: ""
  description: image for tile 3

tile_4_image:
  type: upload
  default: ""
  description: image for tile 4

show_for:
  default: everyone
  type: enum
  choices:
    - everyone
    - logged_in
    - logged_out
